# Generated by Django 4.2.7 on 2024-05-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('country', models.CharField(max_length=255, verbose_name='страна')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('house_number', models.CharField(max_length=255, verbose_name='номер дома')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='задолженность')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('country', models.CharField(max_length=255, verbose_name='страна')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('house_number', models.CharField(max_length=255, verbose_name='номер дома')),
                ('level', models.IntegerField(choices=[(0, 'завод'), (1, 'розничная сеть'), (2, 'индивидуальный предприниматель')], default=0, verbose_name='уровень сети')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.supplier', verbose_name='поставщик')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название товара')),
                ('model', models.CharField(max_length=255, verbose_name='модель')),
                ('release_date', models.DateField(verbose_name='дата выхода продукта на рынок')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributors.tradenetwork', verbose_name='торговая сеть')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
