# Generated by Django 4.2.7 on 2024-05-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tn_level',
            field=models.PositiveIntegerField(default=0, verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tn_children', to='distributors.supplier', verbose_name='родительский поставщик'),
        ),
    ]
