# Generated by Django 4.2.7 on 2024-05-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_alter_supplier_tn_level_alter_supplier_tn_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_structure',
            field=models.CharField(choices=[('завод', 'завод'), ('розничная сеть', 'розничная сеть'), ('индивидуальный предприниматель', 'индивидуальный предприниматель')], default='завод', max_length=255, verbose_name='категория поставщика'),
        ),
    ]
