# Generated by Django 4.2.7 on 2024-05-08 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_alter_supplier_supplier_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
    ]
